version: '3.9'
services:
  nginx:
    image: nginx:1.22
    ports:
      - 8190:80
    volumes:
      - ./deploy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ImOxO8Lz
      MYSQL_DATABASE: x1_community
      MYSQL_USER: x1_community
      MYSQL_PASSWORD: Rc4K3L6f
    ports:
      - 8191:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./deploy/mysql/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: '/usr/bin/mysql --user=x1_community --password=Rc4K3L6f --execute "SHOW DATABASES;"'
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 10
  redis:
    image: redis:6.2
    ports:
      - 8192:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 10
  minio:
    image: bitnami/minio:2022.9.1
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1tQB970y
      MINIO_DEFAULT_BUCKETS: x1-community:download
    ports:
      - 8193:9000
      - 8194:9001
    volumes:
      - minio-data:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "-f",
          "http://minio:9000/minio/health/ready"
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 10
  backend:
    # By default, Compose will pull image from Docker Hub when no local image found.
    image: basicai/xtreme1-backend:v0.7.2
    # Uncomment this line and comment previous line to build image locally, not pull from Docker Hub.
    # build: ./backend
    ports:
      - 8290:8080
    # volumes:
    # Using customized application.yml to override default configs.
    #   - /host/path/to/customized/application.yml:/app/config/application.yml
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "-f",
          "http://backend:8080/actuator/health"
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
  frontend:
    # By default, Compose will pull image from Docker Hub when no local image found.
    image: basicai/xtreme1-frontend:v0.7.2
    # Uncomment this line and comment previous line to build image locally, not pull from Docker Hub.
    # build: ./frontend
    ports:
      - 8291:80
  image-object-detection:
    image: basicai/xtreme1-image-object-detection
    ports:
      - 8292:5000
    # You need to explicitly specify model profile to start this service.
    profiles:
      - model
    runtime: nvidia
  point-cloud-object-detection:
    image: basicai/xtreme1-point-cloud-object-detection
    ports:
      - 8293:5000
    # You need to explicitly specify model profile to start this service.
    profiles:
      - model
    runtime: nvidia
  image-vect-visualization:
    image: basicai/xtreme1-image-vect-visualization
    ports:
      - 8294:5000
  pcd-tools:
    image: basicai/xtreme1-pcd-tools
    ports:
      - 8295:5000
volumes:
  mysql-data:
  redis-data:
  minio-data:
